PATH=/usr/local/bin:./node_modules/.bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11/bin:$HOME/dotfiles/scripts:/usr/local/share/npm/bin:/Users/alex/chromium/depot_tools:/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/bin:/usr/local/Cellar/ruby/2.0.0-p0/lib/ruby/gems/2.0.0/gems/capistrano-2.14.2/bin
export PATH

PHANTOMJS_BIN=/usr/local/share/npm/lib/node_modules/phantomjs
export PHANTOMJS_BIN

# init scripts
. ~/dotfiles/scripts/z.sh
. ~/dotfiles/scripts/git-completion.bash

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

ulimit -n 10000

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Load NVM
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh

# Load ~/.extras, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extras can be used for settings you don’t want to commit
for file in ~/.{extras,bash_prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

for f in ~/dotfiles/extra_scripts/*; do
	[ -r $f ] && source $f;
done;
unset f
